_target_: atria_models.core.local_model.LocalModel
model_name: LayoutLMv3ForQuestionAnswering
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
model_cache_dir: null
model_class:
  path: atria_models.models.layoutlmv3.modeling_layoutlmv3.LayoutLMv3ForQuestionAnswering
  _target_: hydra_zen.funcs.get_obj
