_target_: atria_models.core.local_model.LocalModel
_partial_: false
model_name:
  path: atria_models.models.layoutlmv3.modeling_layoutlmv3.LayoutLMv3ForQuestionAnswering
  _target_: hydra_zen.funcs.get_obj
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: hf://question_answering/microsoft/layoutlmv3-base
