_target_: atria_models.pipelines.classification.image.ImageClassificationPipeline
_partial_: false
defaults:
- /model@model: timm
- /data_transform@runtime_transforms.train: image_instance_tf/default
- /data_transform@runtime_transforms.evaluation: image_instance_tf/default
- /metric@metric_configs.accuracy: accuracy
- /metric@metric_configs.precision: precision
- /metric@metric_configs.recall: recall
- /metric@metric_configs.f1_score: f1_score
- /metric@metric_configs.confusion_matrix: confusion_matrix
- _self_
