_target_: atria_models.pipelines.classification.image.ImageClassificationPipeline
_partial_: false
defaults:
- /model@model: timm
- /data_transform@runtime_transforms.train: image_instance_tf/default
- /data_transform@runtime_transforms.evaluation: image_instance_tf/default
- /metric@metrics.accuracy: accuracy
- /metric@metrics.precision: precision
- /metric@metrics.recall: recall
- /metric@metrics.f1_score: f1_score
- /metric@metrics.confusion_matrix: confusion_matrix
- _self_
pipeline_name: image_classification
config_name: default
mixup_config: null
