_target_: atria_models.pipelines.classification.image.ImageClassificationPipeline
metric_configs:
- _target_: atria_registry.registry_config.RegistryConfig
  name: accuracy
- _target_: atria_registry.registry_config.RegistryConfig
  name: precision
- _target_: atria_registry.registry_config.RegistryConfig
  name: recall
- _target_: atria_registry.registry_config.RegistryConfig
  name: f1_score
- _target_: atria_registry.registry_config.RegistryConfig
  name: confusion_matrix
defaults:
- _self_
- /model@model: timm
- /data_transform@runtime_transforms.train: image/default
- /data_transform@runtime_transforms.evaluation: image/default
