_target_: atria_models.pipelines.classification.layout_token.LayoutTokenClassificationPipeline
metric_configs:
- _target_: atria_registry.registry_config.RegistryConfig
  name: layout_precision
- _target_: atria_registry.registry_config.RegistryConfig
  name: layout_recall
- _target_: atria_registry.registry_config.RegistryConfig
  name: layout_f1
defaults:
- _self_
- /model@model: transformers/token_classification
- /data_transform@runtime_transforms.train: document_instance_tokenizer/sequence_classification
- /data_transform@runtime_transforms.evaluation: document_instance_tokenizer/sequence_classification
