_target_: atria_models.pipelines.classification.layout_token.LayoutTokenClassificationPipeline
_partial_: false
defaults:
- /model@model: transformers/token_classification
- /data_transform@runtime_transforms.train: document_instance_tokenizer/layout_token_classification
- /data_transform@runtime_transforms.evaluation: document_instance_tokenizer/layout_token_classification
- /metric@metrics.layout_precision: layout_precision
- /metric@metrics.layout_recall: layout_recall
- /metric@metrics.layout_f1: layout_f1
- _self_
pipeline_name: layout_token_classification
config_name: default
use_bbox: true
use_image: true
training_overflow_strategy: select_random
evaluation_overflow_strategy: select_all
input_stride: 0
