_target_: atria_models.pipelines.mmdet.object_detection.ObjectDetectionPipeline
_partial_: false
defaults:
- /model@model: mmdet
- /data_transform@runtime_transforms.train: document_instance_mmdet_transform/train
- /data_transform@runtime_transforms.evaluation: document_instance_mmdet_transform/train
- /metric@metrics.cocoeval: cocoeval
- _self_
