_target_: atria_models.pipelines.mmdet.object_detection.ObjectDetectionPipeline
metric_configs:
- _target_: atria_registry.registry_config.RegistryConfig
  name: cocoeval
defaults:
- _self_
- /model@model: mmdet
- /data_transform@runtime_transforms.train: document_instance_mmdet_transform/train
- /data_transform@runtime_transforms.evaluation: document_instance_mmdet_transform/train
