_target_: atria_models.pipelines.mmdet.object_detection.ObjectDetectionPipeline
_partial_: false
defaults:
- _self_
- /model@model: mmdet
model: ???
checkpoint_configs: null
requires_test_time_aug: false
test_time_aug_config:
  _target_: atria_models.pipelines.mmdet.object_detection.TestTimeAugmentationConfig
  nms:
    _target_: atria_models.pipelines.mmdet.object_detection.NMSConfig
    type: nms
    iou_threshold: 0.5
  max_per_img: 100
