_target_: atria_models.pipelines.qa.qa.QuestionAnsweringPipeline
_partial_: false
defaults:
- _self_
- /model@model: transformers/question_answering
model: ???
checkpoint_configs: null
use_bbox: true
use_image: true
training_overflow_strategy: select_random
evaluation_overflow_strategy: select_all
input_stride: 0
