_target_: atria_models.pipelines.qa.qa.QuestionAnsweringPipeline
_partial_: false
defaults:
- _self_
- /model@model: transformers/question_answering
model: ???
checkpoint_configs: null
metrics:
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: sequence_anls
  kwargs: {}
runtime_transforms:
  _target_: atria_core.transforms.base.DataTransformsDict
  train: null
  evaluation: null
use_bbox: true
use_image: true
training_overflow_strategy: select_random
evaluation_overflow_strategy: select_all
input_stride: 0
