_target_: atria_models.pipelines.classification.sequence.SequenceClassificationPipeline
_partial_: false
defaults:
- _self_
- /model@model: transformers/sequence_classification
model: ???
checkpoint_configs: null
use_bbox: true
use_image: true
training_overflow_strategy: select_first
evaluation_overflow_strategy: select_first
