_target_: atria_models.pipelines.classification.sequence.SequenceClassificationPipeline
_partial_: false
defaults:
- /model@model: transformers/sequence_classification
- /data_transform@runtime_transforms.train: document_instance_tokenizer/sequence_classification
- /data_transform@runtime_transforms.evaluation: document_instance_tokenizer/sequence_classification
- /metric@metrics.accuracy: accuracy
- /metric@metrics.precision: precision
- /metric@metrics.recall: recall
- /metric@metrics.f1_score: f1_score
- /metric@metrics.confusion_matrix: confusion_matrix
- _self_
pipeline_name: sequence_classification
config_name: default
use_bbox: true
use_image: true
training_overflow_strategy: select_first
evaluation_overflow_strategy: select_first
input_stride: 0
