_target_: atria_models.pipelines.classification.token.TokenClassificationPipeline
_partial_: false
defaults:
- /model@model: transformers/token_classification
- /data_transform@runtime_transforms.train: document_instance_tokenizer/token_classification
- /data_transform@runtime_transforms.evaluation: document_instance_tokenizer/token_classification
- /metric@metrics.seqeval_accuracy_score: seqeval_accuracy_score
- /metric@metrics.seqeval_precision_score: seqeval_precision_score
- /metric@metrics.seqeval_recall_score: seqeval_recall_score
- /metric@metrics.seqeval_f1_score: seqeval_f1_score
- /metric@metrics.seqeval_classification_report: seqeval_classification_report
- _self_
pipeline_name: token_classification
config_name: default
use_bbox: true
use_image: true
training_overflow_strategy: select_random
evaluation_overflow_strategy: select_all
input_stride: 0
