_target_: atria_models.pipelines.classification.token.TokenClassificationPipeline
_partial_: false
defaults:
- _self_
- /model@model: transformers/token_classification
model: ???
checkpoint_configs: null
metrics:
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: seqeval_accuracy_score
  kwargs: {}
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: seqeval_precision_score
  kwargs: {}
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: seqeval_recall_score
  kwargs: {}
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: seqeval_f1_score
  kwargs: {}
- _target_: atria_models.pipelines.atria_model_pipeline.MetricInitializer
  name: seqeval_classification_report
  kwargs: {}
runtime_transforms:
  _target_: atria_core.transforms.base.DataTransformsDict
  train: null
  evaluation: null
use_bbox: true
use_image: true
training_overflow_strategy: select_random
evaluation_overflow_strategy: select_all
input_stride: 0
