_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_models.core.diffusers_model.DiffusersModel
_zen_partial: false
_zen_exclude:
- name
model_name: ???
num_labels: null
model_cache_dir: null
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
name: diffusers/${.model_name}
