_target_: atria_models.core.timm_model.TimmModel
model_name: ???
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
model_cache_dir: null
