_target_: atria_models.core.transformers_model.TransformersModel
_partial_: false
model_name: transformers
model_cache_dir: null
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
