_target_: atria_models.core.diffusers_model.DiffusersDiffusionModel
_partial_: false
model_name: diffusers/diffusion_model
model_cache_dir: null
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
