_target_: atria_models.core.local_model.LocalModel
_partial_: false
model_name: resnet50
convert_bn_to_gn: false
is_frozen: false
frozen_keys_patterns: null
unfrozen_keys_patterns: null
pretrained_checkpoint: null
model_cache_dir: null
module:
  path: atria_models.models.cifar10_models.resnet50
  _target_: hydra_zen.funcs.get_obj
